# Generated by Django 6.0 on 2025-12-23 05:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="ชื่อลูกค้า")),
                ("phone", models.CharField(max_length=15, verbose_name="เบอร์โทร")),
                (
                    "line_id",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Line ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Dress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="ชื่อชุด")),
                (
                    "image",
                    models.ImageField(upload_to="dresses/", verbose_name="รูปภาพสินค้า"),
                ),
                (
                    "cost_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="ต้นทุนชุด (บาท)"
                    ),
                ),
                (
                    "rental_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="ราคาเช่าต่อครั้ง (บาท)",
                    ),
                ),
                (
                    "is_available",
                    models.BooleanField(default=True, verbose_name="สถานะพร้อมเช่า"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Rental",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="วันที่ยืม")),
                ("end_date", models.DateField(verbose_name="วันที่คืน")),
                (
                    "total_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="ราคารวมรอบนี้"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("BOOKED", "จองแล้ว"),
                            ("ACTIVE", "กำลังเช่า"),
                            ("RETURNED", "คืนแล้ว"),
                        ],
                        default="BOOKED",
                        max_length=10,
                        verbose_name="สถานะ",
                    ),
                ),
                (
                    "note",
                    models.TextField(blank=True, null=True, verbose_name="หมายเหตุ"),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.customer",
                        verbose_name="ลูกค้า",
                    ),
                ),
                (
                    "dress",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.dress",
                        verbose_name="ชุดที่เช่า",
                    ),
                ),
            ],
        ),
    ]
