# Generated by Django 6.0 on 2026-01-02 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Accessory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="ชื่อเครื่องประดับ")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="accessories/",
                        verbose_name="รูปภาพ",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="rental",
            name="accessories",
            field=models.ManyToManyField(
                blank=True, to="core.accessory", verbose_name="เครื่องประดับที่แถม"
            ),
        ),
    ]
