# Generated by Django 6.0 on 2026-01-02 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_accessory_rental_accessories"),
    ]

    operations = [
        migrations.AddField(
            model_name="rental",
            name="deposit",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="ค่ามัดจำ"
            ),
        ),
        migrations.AddField(
            model_name="rental",
            name="price_override",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="ราคาพิเศษ (ถ้ามี)",
            ),
        ),
    ]
